server:
  port: 8080

# Telegram-bot
bot:
  name:
  token:

# Telegram files uri
service:
  file-info:
    uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
  file-storage:
    uri: https://api.telegram.org/file/bot{token}/{filePath}

spring:

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username:
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  # RabbitMQ
  rabbitmq:
    username: guest
    password: guest
    queue-name: send.mail
    exchange-name: exchange

# Crypto
cipher:
  initVector: F-JaNdRgUjXn2r5u
  key: hVmYp3s6v9y$B&E)
