# database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mailsenderdb
    username: postgres
    password: martin12
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#  rabbitMQ
  rabbitmq:
    addresses: localhost
    port: 15672
    username: guest
    password: guest
    queue-name: send.mail
#  for send-worker
base:
  mails: stepankonasenko@gmail.com
  keys: pkjjmwzhblochwaz
