server:
  port: 8081
bot:
  name:
  token:
service:
  file-info:
    uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
  file-storage:
    uri: https://api.telegram.org/file/bot{token}/{filePath}
# database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username:
    password:
  jpa:
    generate-ddl: false
    show-sql: true
#  rabbitMQ
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    queue-name: send.mail
#  for send-worker
base:
  mails:
  keys:
#for Crypto
cipher:
  initVector: F-JaNdRgUjXn2r5u
  key: hVmYp3s6v9y$B&E)

