package org.gnori.shared.utils;

public enum CryptoFailure {

    ENCRYPT_FAILURE,
    DECRYPT_FAILURE,
    UNSUPPORTED_ENCODING_EXCEPTION,
    NO_SUCH_ALGORITHM_EXCEPTION,
    NO_SUCH_PADDING_EXCEPTION,
    INVALID_KEY_EXCEPTION,
    INVALID_ALGORITHM_PARAMETER_EXCEPTION,
    ILLEGAL_BLOCK_SIZE_EXCEPTION,
    BAD_PADDING_EXCEPTION
}
